### ISSUE TITLE
Spotify calls receiving 401 (and associated fallout)

### ISSUE THREAD

**Issue by davidsharp** [yianL/atom-spotified#13]
I noticed the album artwork wasn't showing up for me any more, my Atom console is logging `401` errors from the Spotify servers, which was resulting in `atom-spotified` using the 'offline' props, which don't include the album artwork.

Since we get a URL through from `getTrack.applescript`, I'm using it here: https://github.com/yianL/atom-spotified/compare/master...davidsharp:patch-2

However, as it's just a quick fix that doesn't account for being offline, it will show a broken image when the image call fails. So I've not created a pull request yet.

I feel that the deeper problem is that I'm getting these 401 errors, which I assume is a rate limit or something, which makes me think that we might _have_ to rely on the AppleScript artwork_url value.

**Comment by archcorsair** [comment]
I'm having the same issue (No album artwork), console is reporting:

`spotify-poller.js [sm]:44 GET https://api.spotify.com/v1/tracks/1EDVfFvmSSTFGHC9EVUauV 401 (Unauthorized)`

`spotify-poller.js [sm]:65 spotify api error: Error: Spotify API request failed
    at /Users/<User>/.atom/packages/atom-spotified/src/utils/spotify-poller.js:47:19`

**Comment by yianL** [comment]
I believe Spotify made a change to require authorization for all their API endpoints, thus the 401 errors. If the AppleScript api does provide artwork_url, that might be the easiest fix for this. Otherwise either the plugin has to ask for user's spotify credential, or I'll have to host a proxy somewhere that does not require authorization, both of which are less ideal.

**Comment by yianL** [comment]
Turns out `artwork_url` value worked pretty well. `v0.8.1` removes the spotify web api call. Thanks for reporting this!
